[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "HolograPy"
version = "0.1.0"
description = "A holography simulation and visualization package"
readme = "README.md"
requires-python = ">=3.8"

authors = [
    { name = "James Hardwick" }
]

license = "MIT"

classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Physics",
]

dependencies = [
    "numpy",
    "Pillow",
    "plotly",
]
