[metadata]
name = HolograPy
version = 0.1.0
author = James Hardwick
description = Tools for holography in Python
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/JamesAHardwick/HolograPy
license = MIT

[options]
packages = find:
install_requires =
    numpy
    matplotlib
python_requires = >=3.9
